name: Release Workflow

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Increment version, update files, and create release
        run: |
          # Extract the current version from the plugin file
          VERSION=$(grep -oP 'Version:\s*\K[\d.]+' asasvirtuais-wp.php)
          IFS='.' read -ra VERSION_PARTS <<< "$VERSION"
          PATCH=${VERSION_PARTS[2]}
          # Check if PATCH is 0, indicating a new minor or major version, and do not increment
          if [ "$PATCH" -ne 0 ]; then
            NEW_PATCH=$((PATCH + 1))
          else
            NEW_PATCH=$PATCH
          fi
          NEW_VERSION="${VERSION_PARTS[0]}.${VERSION_PARTS[1]}.$NEW_PATCH"
          # Update the version in the plugin file
          sed -i "s/Version:\s*$VERSION/Version: $NEW_VERSION/" asasvirtuais-wp.php

          # Update the version in composer.json
          jq '.version = "'$NEW_VERSION'"' composer.json > tmp.$$.json && mv tmp.$$.json composer.json

          # Update the version in metadata.json
          jq '.version = "'$NEW_VERSION'"' metadata.json > tmp.$$.json && mv tmp.$$.json metadata.json

          # Run composer install to update vendors
          composer install

          # Create a zip file with the source code including asasvirtuais-wp.php at root and vendors
          zip -r "asasvirtuais-wp.zip" asasvirtuais-wp.php vendor src

          # Commit and push the version updates
          git config --global user.email "39817766+asas-virtuais@users.noreply.github.com"
          git config --global user.name "Icaro Asas Virtuais"
          git add asasvirtuais-wp.php composer.json composer.lock metadata.json
          git commit -m "Update version to $NEW_VERSION"
          git push

          # Create a new release
          gh release create "$NEW_VERSION" --notes-file -
          # Upload the zip file as a release asset
          gh release upload "$NEW_VERSION" asasvirtuais-wp.zip --clobber

          echo "$RELEASE_NOTES"

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}